import mongoose, { Schema } from 'mongoose';
import type { JWTData } from '$lib/server/auth';
import User from '$lib/server/db/models/User';

const SessionSchema: Schema = new Schema({
	userId: { type: mongoose.Schema.Types.ObjectId, required: true },
	timestamp: { type: Date, required: true, default: Date.now },
	sessionId: { type: String, required: true },
	userAgent: { type: String }
});

SessionSchema.statics.createSession = async function (
	jwt: JWTData,
	userAgent: string
): Promise<ISession> {
	if (typeof jwt.sub !== 'string' || typeof jwt.jti !== 'string')
		throw new Error('Invalid JWT: Abort create session.');

	const user = await User.findOne({ emailAddress: jwt.sub }).exec();
	if (!user) throw new Error('User not found');

	return await this.create({ userId: user, sessionId: jwt.jti, userAgent });
};

SessionSchema.statics.getUserSessions = async function (userId: string): Promise<ISession[]> {
	const user = await User.findById(userId).exec();
	if (!user) throw new Error('User not found');

	return await this.find({ userId: user.id }).exec();
};

export interface ISession extends mongoose.Document {
	/**
	 * The ID of the User Document in the database that this session belongs to.
	 */
	userId: mongoose.Types.ObjectId;

	/**
	 * The timestamp of when the session was created.
	 */
	timestamp: Date;

	/**
	 * The session ID of the session. This is used to uniquely identify the
	 * session and match it with the user's JWT.
	 */
	sessionId: string;

	/**
	 * The user agent that was used to create the session. This is used to
	 * identify the device that the session was created on for the user's
	 * session history.
	 */
	userAgent?: string;
}

export interface ISessionModel extends mongoose.Model<ISession> {
	/**
	 * Creates a new session in the database with the given JWT and user agent.
	 * @param jwt The JWT generated by the authentication utilities upon login.
	 * @param userAgent The user agent of the device that the session was created on.
	 */
	createSession(jwt: JWTData, userAgent: string): Promise<ISession>;

	/**
	 * Retrieves all sessions that belong to the user with the given ID.
	 * @param userId The MongoDB Document ID of the user to get the sessions for.
	 */
	getUserSessions(userId: string): Promise<ISession[]>;
}

// Create the Session model
let Session: ISessionModel;

try {
	Session = mongoose.model<ISession, ISessionModel>('Session', SessionSchema);
} catch (e) {
	if (e instanceof mongoose.Error.OverwriteModelError)
		Session = mongoose.model<ISession, ISessionModel>('Session');
	else throw e;
}

export default Session;
